library(readxl)
library(dplyr)
attach(table_1)
attach(data2)
left_join(table_1,data2,by="Reg No")
x=left_join(table_1,data2,by="Reg No")
View(x)
right_join(table_1,data2,by="Reg No")
Y=right_join(table_1,data2,by="Reg No")
View(Y)
